### ISSUE TITLE
Invalid proxy base when exposed under a subdomain

### ISSUE THREAD

**Issue by acsgn** [canonical/spark-history-server-k8s-operator#68]
## Steps to reproduce
```
bundle: kubernetes
applications:
  s3:
    charm: s3-integrator
    channel: latest/stable
    scale: 1
    options:
      bucket: history-server
      endpoint: http://spark-minio:9000
      path: spark-events
  spark-minio:
    charm: minio
    channel: ckf-1.9/stable
    scale: 1
    _github_repo_name: minio-operator
    _github_repo_branch: track/ckf-1.9
    options:
      access-key: s3key
      secret-key: s3secret
  history-server:
    charm: spark-history-server-k8s
    channel: 3.4/stable
    resources:
      spark-history-server-image: 15
    scale: 1
    constraints: arch=amd64
  traefik:
    charm: traefik-k8s
    channel: latest/stable
    scale: 1
    options:
      routing_mode: subdomain
      external_hostname: example.com
    trust: true
relations:
- - traefik:ingress
  - history-server:ingress
- - history-server:s3-credentials
  - s3:s3-credentials
```
1. Create a model named Spark
2. Create bucket and a file as spark-events/dummy
3. Sync S3 credentials
4. Go to spark-history-server.example.com

## Expected behavior
Website functions normally

## Actual behavior
Website references // resources, which resolves to file URIs and fails to load

https://github.com/canonical/spark-history-server-k8s-operator/blob/6b54176f0a7be1345a8d88868234de0c41323210/src/managers/history_server.py#L49-L57

![Image](https://github.com/user-attachments/assets/05d0f348-dbdd-4b22-9e9b-c465bc288381)

![Image](https://github.com/user-attachments/assets/a36d2cfb-8252-4e1d-a64b-cf9474510e14)

## Versions

Operating system: 
Ubuntu 22.04.3 LTS

Juju CLI: 
3.6.4-genericlinux-amd64

Juju agent: 
3.6.4

Charm revision: 
28

microk8s: 
MicroK8s v1.32.2 revision 7731
